a.out: 01.o aislower.o aisupper.o atolower.o atoupper.o astrcmp.o astrncmp.o astrcasecmp.o astrncasecmp.o aisalpha.o aisdigit.o aisalnum.o aisxdigit.o
	gcc  01.o aislower.o aisupper.o atolower.o atoupper.o astrcmp.o astrncmp.o astrcasecmp.o astrncasecmp.o aisalpha.o aisdigit.o aisalnum.o aisxdigit.o
01.o : 01.c
	gcc -c 01.c

aislower.o : aislower.c
	gcc -c aislower.c

aisupper.o : aisupper.c
	gcc -c aisupper.c

atolower.o : atolower.c
	gcc -c atolower.c

atoupper.o : atoupper.c
	gcc -c atoupper.c

astrcmp.o : astrcmp.c
	gcc -c astrcmp.c

astrncmp.o : astrncmp.c
	gcc -c astrncmp.c

astrcasecmp.o : astrcasecmp.c
	gcc -c astrcasecmp.c

astrncasecmp.o : astrncasecmp.c
	gcc -c astrncasecmp.c

aisalpha.o : aisalpha.c
	gcc -c aisalpha.c

aisdigit.o : aisdigit.c
	gcc -c aisdigit.c

aisalnum.o : aisalnum.c
	gcc -c aisalnum.c

aisxdigit.o : aisxdigit.c
	gcc -c aisxdigit.c
clean :
	rm -rf 01.o 
	rm -rf aislower.o 
	rm -rf aisupper.o 
	rm -rf atolower.o 
	rm -rf atoupper.o 
	rm -rf astrcmp.o  
	rm -rf astrncmp.o  
	rm -rf astrcasecmp.o 
	rm -rf astrncasecmp.o 
	rm -rf aisalpha.o 
	rm -rf aisdigit.o 
	rm -rf aisalnum.o

